package com.mac.mapper.mac;

import com.mac.model.mac.User;

public interface UserMapper {


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    int insert(User record);

}