package com.mac.mapper.win;


import com.mac.model.win.Country;

public interface CountryMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table country
     *
     * @mbggenerated
     */
    int insert(Country record);

}